#!/bin/bash
# 測試 sdl 的 set 語法

echo "=== 測試 SDL SET 語法 ==="
echo ""
echo "這個腳本展示三種 sdl 語法的使用方式"
echo ""

# 測試指令列表
commands=(
    "# === 範例 1: 創建並設置 ammy ==="
    "create person ammy 帥氣的冒險者"
    "summon ammy"
    "set ammy 性別 男"
    "set ammy 力量 120"
    "set ammy 顏值 85"
    "set ammy mp 95000"
    ""
    "# 使用三種不同語法設置對話"
    "# 語法 1: 簡單版"
    "sdl ammy 見面 嗨！好久不見"
    ""
    "# 語法 2: add 語法"
    "sdl ammy 閒聊 add 今天狀態不錯 when mp>90000"
    ""
    "# 語法 3: set 語法（新！）"
    "sdl ammy set 閒聊 when 力量>100 and 顏值>80 say 你真是又帥又厲害"
    "sdl ammy set 閒聊 when 力量>100 and 顏值<80 say 你的力量很強"
    "sdl ammy set 閒聊 when mp<90000 say 今天有點累"
    ""
    "# 查看 ammy 的對話設置"
    "check ammy"
    ""
    "# 測試對話"
    "talk ammy 見面"
    "talk ammy 閒聊"
    "talk ammy 閒聊"
    "talk ammy 閒聊"
    ""
    "# === 範例 2: 商人的物品數量條件 ==="
    "create person 商人 精明的商人"
    "summon 商人"
    ""
    "sdl 商人 閒聊 歡迎光臨！"
    "sdl 商人 set 閒聊 when 物品數量>5 say 要不要賣些東西給我"
    "sdl 商人 set 閒聊 when 物品數量<3 say 看來你身無長物啊"
    "sdl 商人 set 閒聊 when 物品數量>=3 and 物品數量<=5 say 你的東西不多不少"
    ""
    "# 測試不同物品數量的對話"
    "talk 商人 閒聊"
    "talk 商人 閒聊"
    ""
    "get 麵包"
    "get 火把"
    "talk 商人 閒聊"
    ""
    "get 繩索"
    "get 匕首"
    "get 弓"
    "get 箭"
    "talk 商人 閒聊"
    "talk 商人 閒聊"
    ""
    "# === 範例 3: 複雜條件組合 ==="
    "create person 櫻花 可愛的女孩"
    "summon 櫻花"
    "set 櫻花 性別 女"
    "set 櫻花 顏值 90"
    "set 櫻花 mp 80000"
    ""
    "sdl 櫻花 set 閒聊 when 性別=女 and 顏值>80 and mp>70000 say 你好漂亮又有精神！"
    "sdl 櫻花 set 閒聊 when 性別=女 and 顏值>80 say 你真漂亮"
    "sdl 櫻花 set 閒聊 when mp>70000 say 你看起來精神很好"
    "sdl 櫻花 閒聊 天氣不錯呢"
    ""
    "talk 櫻花 閒聊"
    "talk 櫻花 閒聊"
    "talk 櫻花 閒聊"
    ""
    "# 改變 mp 後再測試"
    "set 櫻花 mp 60000"
    "talk 櫻花 閒聊"
    "talk 櫻花 閒聊"
)

echo "開始執行測試命令..."
echo ""

for cmd in "${commands[@]}"; do
    if [[ "$cmd" == \#* ]]; then
        echo ""
        echo "$cmd"
    elif [ -z "$cmd" ]; then
        sleep 0.5
    else
        echo "> $cmd"
        sleep 0.3
    fi
done

echo ""
echo "=== 測試完成 ==="
echo ""
echo "總結："
echo "- 語法 1 (簡單版): sdl <NPC> <話題> <對話>"
echo "- 語法 2 (add): sdl <NPC> <話題> add <對話> when <條件>"
echo "- 語法 3 (set): sdl <NPC> set <話題> when <條件> say <對話>"
echo ""
echo "語法 3 的優點：條件在前，對話在後，更直觀！"
