#!/bin/bash
# 測試對話系統條件評估（修復後）

echo "=== 測試對話條件評估 ==="
echo ""
echo "此測試展示 NPC 如何根據**玩家**的屬性來選擇對話"
echo ""

commands=(
    "# === 設置測試場景 ==="
    "create person 櫻花 可愛的女孩"
    "summon 櫻花"
    ""
    "# === 設置玩家屬性 ==="
    "set me 性別 女"
    "set me 顏值 85"
    "set me mp 95000"
    ""
    "# === 設置 NPC 對話（根據玩家屬性的條件）==="
    "sdl 櫻花 set 閒聊 when 顏值>80 and 性別=女 say 你長得好漂亮啊！"
    "sdl 櫻花 set 閒聊 when mp>90000 say 你看起來精神很好呢"
    "sdl 櫻花 set 閒聊 when 顏值<80 say 你好呀~"
    "sdl 櫻花 閒聊 今天天氣不錯"
    ""
    "# === 測試 1: 玩家符合高顏值+女性條件 ==="
    "check me"
    "talk 櫻花 閒聊"
    "talk 櫻花 閒聊"
    "talk 櫻花 閒聊"
    ""
    "# === 測試 2: 修改玩家顏值後再測試 ==="
    "set me 顏值 60"
    "check me"
    "talk 櫻花 閒聊"
    "talk 櫻花 閒聊"
    ""
    "# === 測試 3: 測試物品數量條件 ==="
    "create person 商人 精明的商人"
    "summon 商人"
    ""
    "sdl 商人 set 閒聊 when 物品數量>5 say 要不要賣些東西給我？"
    "sdl 商人 set 閒聊 when 物品數量<=5 say 需要買點東西嗎？"
    ""
    "# 玩家物品少時"
    "talk 商人 閒聊"
    "talk 商人 閒聊"
    ""
    "# 撿起更多物品"
    "get 麵包"
    "get 火把"
    "get 繩索"
    "get 匕首"
    "get 弓"
    "get 箭"
    ""
    "# 玩家物品多時"
    "talk 商人 閒聊"
    "talk 商人 閒聊"
    ""
    "# === 測試 4: 複雜條件組合 ==="
    "create person 教練 嚴格的訓練師"
    "summon 教練"
    ""
    "set me 力量 120"
    ""
    "sdl 教練 set 閒聊 when 力量>100 and mp>90000 say 你的狀態很好，繼續保持！"
    "sdl 教練 set 閒聊 when 力量>100 and mp<90000 say 力量不錯，但要多休息"
    "sdl 教練 set 閒聊 when 力量<100 say 還需要多鍛鍊"
    ""
    "talk 教練 閒聊"
    "talk 教練 閒聊"
    ""
    "set me mp 50000"
    "talk 教練 閒聊"
    "talk 教練 閒聊"
)

echo "開始執行測試..."
echo ""

for cmd in "${commands[@]}"; do
    if [[ "$cmd" == \#* ]]; then
        echo ""
        echo "$cmd"
    elif [ -z "$cmd" ]; then
        sleep 0.3
    else
        echo "> $cmd"
        sleep 0.2
    fi
done

echo ""
echo "=== 測試完成 ==="
echo ""
echo "📝 總結："
echo "- NPC 的對話條件是根據**玩家**的屬性來評估"
echo "- 玩家的顏值、性別、物品數量、力量等都會影響 NPC 的回應"
echo "- 這讓對話更加動態和個性化"
