#!/bin/bash

# 測試戰鬥技能台詞整合
echo "=== 測試戰鬥技能台詞系統整合 ==="
echo ""
echo "現在戰鬥技能台詞已整合到一般對話系統中"
echo "可以使用 sdl 指令設定戰鬥技能的台詞"
echo ""
echo "測試步驟："
echo ""
echo "1. 啟動遊戲："
echo "   cargo run"
echo ""
echo "2. 設定NPC的戰鬥技能台詞："
echo "   sdl 商人 punch 你敢打我？"
echo "   sdl 商人 kick 住手！"
echo ""
echo "3. 靠近NPC並攻擊："
echo "   flyto 3,3"
echo "   punch 商人"
echo ""
echo "4. 觀察NPC反擊時的台詞："
echo "   - 應該看到NPC使用你設定的台詞"
echo "   - 例如：💥 商人 說：「你敢打我？」造成 2 點傷害！"
echo ""
echo "5. 測試玩家自己的技能台詞："
echo "   sdl me punch 我的鐵拳！"
echo "   punch 商人"
echo "   - 應該看到：💥 me 說：「我的鐵拳！」造成 2 點傷害！"
echo ""
echo "6. 測試條件式台詞（進階）："
echo "   sdl 商人 punch add 你欺負弱小！ when 血量<50"
echo "   # 打到商人血量低時，觀察台詞是否改變"
echo ""
echo "優勢："
echo "- ✅ 不需要額外的技能台詞設定指令"
echo "- ✅ 支援條件式台詞"
echo "- ✅ 支援多個台詞選項（隨機）"
echo "- ✅ 統一的台詞管理系統"
